steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: push_source
    args: 
      - gsutil
      - -m
      - rsync
      - -rd
      - -x
      - ".git/"
      - .
      - gs://crypto-arb-resources/repositories/$REPO_NAME