from ...enums import InstrumentType, Symbol

instrument_names = {
    InstrumentType.SPOT: {
        Symbol.ADA: "ADAUSDT",
        Symbol.ALTMEXT: "ALTMEXTUSDT",
        Symbol.APE: "APEUSDT",
        Symbol.AVAX: "AVAXUSDT",
        Symbol.BCH: "BCHUSDT",
        Symbol.BNB: "BNBUSDT",
        Symbol.DEFIMEXT: "DEFIMEXTUSDT",
        Symbol.DOGE: "DOGEUSDT",
        Symbol.DOT: "DOTUSDT",
        Symbol.EOS: "EOSUSDT",
        Symbol.ETH: "ETHUSDT",
        Symbol.FTM: "FTMUSDT",
        Symbol.GAL: "GALUSDT",
        Symbol.GMT: "GMTUSDT",
        Symbol.LINK: "LINKUSDT",
        Symbol.LTC: "LTCUSDT",
        Symbol.MANA: "MANAUSDT",
        Symbol.MATIC: "MATICUSDT",
        Symbol.METAMEXT: "METAMEXTUSDT",
        Symbol.NEAR: "NEARUSDT",
        Symbol.SAND: "SANDUSDT",
        Symbol.SHIB: "SHIBUSDT",
        Symbol.SOL: "SOLUSDT",
        Symbol.TRX: "TRXUSDT",
        Symbol.XBT: "XBTUSDT",
        Symbol.XRP: "XRPUSDT",
    },
    InstrumentType.SPOT: {
        Symbol.APE: "APE_USDT",
        Symbol.AXS: "AXS_USDT",
        Symbol.ETH: "ETH_USDT",
        Symbol.LINK: "LINK_USDT",
        Symbol.MATIC: "MATIC_USDT",
        Symbol.UNI: "UNI_USDT",
        Symbol.XBT: "XBT_USDT",
    },
}
