from pyutil.enums import NameEnum


class OHLCVColumn(NameEnum):
    "Column names for OHLCV data feed"

    open_time = "open_time"
    open = "open"
    high = "high"
    low = "low"
    close = "close"
    volume = "volume"
    returns = "returns"
    funding_rate = "funding_rate"


class Instrument(NameEnum):
    """Column names for Exchange active_instruments"""

    symbol = "symbol"
    instType = "instType"
    contract_name = "contract_name"
    listing_date = "listing_date"


class OrderBookSchema(NameEnum):
    "Column Schema for Order Book data structure"

    price = "price"
    """Price of order"""

    quantity = "quantity"
    """Quantity of order"""

    side = "side"
    """See OrderBookSide"""

    timestamp = "timestamp"
    """Timestamp of snapshot"""


class OrderBookSide(NameEnum):
    """Possible values for OrderBookSchema.side"""

    ask = "a"
    bid = "b"


class FundingRateSchema(NameEnum):
    "Column Schema for Funding rate structure"
    symbol = "symbol"

    timestamp = "timestamp"
    """Timestamp of Funding Rate"""

    funding_rate = "funding_rate"
    """Value of Funding Rate """


class Exchange(NameEnum):
    """Names of registered exchanges in the API"""

    BINANCE = "binance"
    BITMEX = "bitmex"
    BYBIT = "bybit"
    COINFLEX = "coinflex"
    FTX = "ftx"
    OKEX = "okex"
    GATEIO = "gateio"
    KUCOIN = "kucoin"


class InstrumentType(NameEnum):
    """Names of registered instrument types in the API"""

    PERPETUAL = "perpetual"
    PERP = "perpetual"
    QUARTERLY = "quarterly"
    MONTHLY = "monthly"


class Interval(NameEnum):
    """Names of registered historical candlestick data intervals in the API"""

    interval_1m = "interval_1m"
    interval_3m = "interval_3m"
    interval_5m = "interval_5m"
    interval_15m = "interval_15m"
    interval_30m = "interval_30m"
    interval_1h = "interval_1h"
    interval_2h = "interval_2h"
    interval_4h = "interval_4h"
    interval_6h = "interval_6h"
    interval_8h = "interval_8h"
    interval_12h = "interval_12h"
    interval_1d = "interval_1d"
    interval_3d = "interval_3d"
    interval_1w = "interval_1w"


class Symbol(NameEnum):
    """Names of registered symbols in the API"""

    _1000SHIB = "_1000SHIB"
    _1000XEC = "_1000XEC"
    _1INCH = "_1INCH"
    AAVE = "AAVE"
    ACH = "ACH"
    ADA = "ADA"
    AGLD = "AGLD"
    AKRO = "AKRO"
    ALCX = "ALCX"
    ALGO = "ALGO"
    ALICE = "ALICE"
    ALPHA = "ALPHA"
    ALT = "ALT"
    AMPL = "AMPL"
    ANC = "ANC"
    ANKR = "ANKR"
    ANT = "ANT"
    AR = "AR"
    ARPA = "ARPA"
    ASD = "ASD"
    ATA = "ATA"
    ATLAS = "ATLAS"
    ATOM = "ATOM"
    AUDIO = "AUDIO"
    AVAX = "AVAX"
    AXS = "AXS"
    BABYDOGE = "BABYDOGE"
    BADGER = "BADGER"
    BAKE = "BAKE"
    BAL = "BAL"
    BAND = "BAND"
    BAO = "BAO"
    BAT = "BAT"
    BCD = "BCD"
    BCH = "BCH"
    BEAM = "BEAM"
    BEL = "BEL"
    BICO = "BICO"
    BIT = "BIT"
    BLZ = "BLZ"
    BNB = "BNB"
    BNT = "BNT"
    BOBA = "BOBA"
    BRZ = "BRZ"
    BSV = "BSV"
    BTC = "BTC"
    BTCBUSD = "BTCBUSD"
    BTCDOM = "BTCDOM"
    BTM = "BTM"
    BTS = "BTS"
    BTT = "BTT"
    BZZ = "BZZ"
    C98 = "C98"
    CAKE = "CAKE"
    CEL = "CEL"
    CELO = "CELO"
    CELR = "CELR"
    CERE = "CERE"
    CFX = "CFX"
    CHR = "CHR"
    CHZ = "CHZ"
    CKB = "CKB"
    CLV = "CLV"
    COMP = "COMP"
    CONV = "CONV"
    COTI = "COTI"
    CQT = "CQT"
    CREAM = "CREAM"
    CRO = "CRO"
    CRU = "CRU"
    CRV = "CRV"
    CSPR = "CSPR"
    CTK = "CTK"
    CTSI = "CTSI"
    CUSDT = "CUSDT"
    CVC = "CVC"
    DASH = "DASH"
    DAWN = "DAWN"
    DEFI = "DEFI"
    DEGO = "DEGO"
    DENT = "DENT"
    DGB = "DGB"
    DODO = "DODO"
    DOGE = "DOGE"
    DORA = "DORA"
    DOT = "DOT"
    DRGN = "DRGN"
    DUSK = "DUSK"
    DYDX = "DYDX"
    EDEN = "EDEN"
    EFI = "EFI"
    EGLD = "EGLD"
    ELON = "ELON"
    ENJ = "ENJ"
    ENS = "ENS"
    EOS = "EOS"
    ETC = "ETC"
    ETH = "ETH"
    EXCH = "EXCH"
    FIDA = "FIDA"
    FIL = "FIL"
    FLEX = "FLEX"
    FLM = "FLM"
    FLOW = "FLOW"
    FRONT = "FRONT"
    FTM = "FTM"
    FTT = "FTT"
    GALA = "GALA"
    GITCOIN = "GITCOIN"
    GODS = "GODS"
    GRIN = "GRIN"
    GRT = "GRT"
    GTC = "GTC"
    HBAR = "HBAR"
    HIVE = "HIVE"
    HNT = "HNT"
    HOLY = "HOLY"
    HOT = "HOT"
    HT = "HT"
    HUM = "HUM"
    ICP = "ICP"
    ICX = "ICX"
    ILV = "ILV"
    IMX = "IMX"
    IOST = "IOST"
    IOTA = "IOTA"
    IOTX = "IOTX"
    IRIS = "IRIS"
    JASMY = "JASMY"
    JST = "JST"
    KAVA = "KAVA"
    KEEP = "KEEP"
    KIN = "KIN"
    KISHU = "KISHU"
    KLAY = "KLAY"
    KNC = "KNC"
    KSHIB = "KSHIB"
    KSM = "KSM"
    LAT = "LAT"
    LDO = "LDO"
    LEO = "LEO"
    LINA = "LINA"
    LINK = "LINK"
    LIT = "LIT"
    LON = "LON"
    LPT = "LPT"
    LRC = "LRC"
    LTC = "LTC"
    LUNA = "LUNA"
    MAKITA = "MAKITA"
    MANA = "MANA"
    MAPS = "MAPS"
    MASK = "MASK"
    MATIC = "MATIC"
    MBABYDOGE = "MBABYDOGE"
    MBOX = "MBOX"
    MCB = "MCB"
    MEDIA = "MEDIA"
    MELON = "MELON"
    MER = "MER"
    MID = "MID"
    MINA = "MINA"
    MIR = "MIR"
    MKISHU = "MKISHU"
    MKR = "MKR"
    MNGO = "MNGO"
    MOVR = "MOVR"
    MTA = "MTA"
    MTL = "MTL"
    MVDA10 = "MVDA10"
    MVDA25 = "MVDA25"
    NEAR = "NEAR"
    NEO = "NEO"
    NEST = "NEST"
    NFT = "NFT"
    NKN = "NKN"
    NU = "NU"
    OCEAN = "OCEAN"
    OGN = "OGN"
    OKB = "OKB"
    OMG = "OMG"
    ONE = "ONE"
    ONT = "ONT"
    ORBS = "ORBS"
    OXY = "OXY"
    PAXG = "PAXG"
    PEARL = "PEARL"
    PEOPLE = "PEOPLE"
    PERP = "PERP"
    POLIS = "POLIS"
    POLS = "POLS"
    POLY = "POLY"
    POND = "POND"
    PRIV = "PRIV"
    PROM = "PROM"
    PUNDIX = "PUNDIX"
    QTUM = "QTUM"
    RACA = "RACA"
    RAD = "RAD"
    RAMP = "RAMP"
    RAY = "RAY"
    REEF = "REEF"
    REN = "REN"
    REQ = "REQ"
    REVV = "REVV"
    RLC = "RLC"
    RNDR = "RNDR"
    ROOK = "ROOK"
    ROSE = "ROSE"
    RSR = "RSR"
    RUNE = "RUNE"
    RVN = "RVN"
    SAND = "SAND"
    SC = "SC"
    SECO = "SECO"
    SERO = "SERO"
    SFP = "SFP"
    SHIB = "SHIB"
    SHIB1000 = "SHIB1000"
    SHIT = "SHIT"
    SKL = "SKL"
    SLP = "SLP"
    SNX = "SNX"
    SOL = "SOL"
    SPELL = "SPELL"
    SRM = "SRM"
    SRN = "SRN"
    STARL = "STARL"
    STEP = "STEP"
    STMX = "STMX"
    STORJ = "STORJ"
    STX = "STX"
    SUN = "SUN"
    SUPER = "SUPER"
    SUSHI = "SUSHI"
    SWRV = "SWRV"
    SXP = "SXP"
    TFUEL = "TFUEL"
    THETA = "THETA"
    TLM = "TLM"
    TOMO = "TOMO"
    TONCOIN = "TONCOIN"
    TORN = "TORN"
    TRB = "TRB"
    TRIBE = "TRIBE"
    TRU = "TRU"
    TRX = "TRX"
    TRYB = "TRYB"
    TULIP = "TULIP"
    UMA = "UMA"
    UNFI = "UNFI"
    UNI = "UNI"
    UNISWAP = "UNISWAP"
    USDT = "USDT"
    VET = "VET"
    VRA = "VRA"
    WAVES = "WAVES"
    WAXP = "WAXP"
    WNCG = "WNCG"
    WNXM = "WNXM"
    WOO = "WOO"
    WSB = "WSB"
    XAUG = "XAUG"
    XAUT = "XAUT"
    XCH = "XCH"
    XEC = "XEC"
    XEM = "XEM"
    XLM = "XLM"
    XMR = "XMR"
    XRP = "XRP"
    XTZ = "XTZ"
    XVS = "XVS"
    YFI = "YFI"
    YFII = "YFII"
    YGG = "YGG"
    ZEC = "ZEC"
    ZEN = "ZEN"
    ZIL = "ZIL"
    ZKS = "ZKS"
    ZRX = "ZRX"
